language: cpp

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=linux
      sudo: required
      compiler: gcc-7
      addons:
        apt:
          config:
            retries: true
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - zlib1g-dev
            - gtk+-3.0
            - openssl
            # Boost, Lua and SDL2 library versions provided are too old, they must be compiled manually.
    - os: osx
      env:
        - BUILD_TYPE=osx
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl/
      compiler: clang
    - os: linux
      env: BUILD_TYPE=android
      language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - extra-google-m2repository
          - extra-android-m2repository

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
    - MAKEFLAGS=-j8

cache:
  directories:
    - $HOME/.ccache
    - $HOME/download

before_install:
  - if [[ "$BUILD_TYPE" == "osx" ]]; then
      brew update &&
      brew upgrade cmake boost &&
      brew install sdl2 sdl2_ttf sdl2_image sdl2_mixer lua openssl clang-format;
    fi
  - if [[ "$BUILD_TYPE" == "linux" ]]; then
      export CC="gcc-7";
      export CXX="g++-7";
      gcc -v && g++ -v;
    fi
  - if [[ "$BUILD_TYPE" == "android" ]]; then
      yes | sdkmanager "ndk-bundle";
      yes | sdkmanager "cmake;3.6.4111459";
      yes | sdkmanager "lldb;3.1";
    fi
  - if [[ "$BUILD_TYPE" == "linux" ]]; then . "$TRAVIS_BUILD_DIR/.travis/before_install.sh"; fi

install:
  - if [[ "$BUILD_TYPE" == "linux" ]]; then
      export CC="gcc-7";
      export CXX="g++-7";
      gcc -v && g++ -v;
    fi
  - if [[ "$BUILD_TYPE" == "linux" ]]; then . "$TRAVIS_BUILD_DIR/.travis/install.sh"; fi

before_script:
  - if [[ "$BUILD_TYPE" == "android" ]]; then
      export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle;
      (echo -e "ndk.dir=$ANDROID_NDK_HOME\nsdk.dir=$ANDROID_HOME" > "$TRAVIS_BUILD_DIR/android/local.properties");
    fi

script:
  - cd "$TRAVIS_BUILD_DIR";
  - if [[ "$BUILD_TYPE" != "android" ]]; then
      make putit;
    fi
  - if [[ "$BUILD_TYPE" == "osx" ]]; then
      make format;
    fi
  - if [[ "$BUILD_TYPE" == "linux" ]]; then
      export CC="gcc-7";
      export CXX="g++-7";
      export LD_LIBRARY_PATH="/usr/lib:$LD_LIBRARY_PATH";
      export LD_RUN_PATH="/usr/lib:$LD_RUN_PATH";
      export CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=TRUE";
      gcc -v && g++ -v;
      export AUDIODEV=null;
    fi
  - env
  - cd "$TRAVIS_BUILD_DIR/deps"
  - wget --no-verbose "http://ylvania.style.coocan.jp/file/elona122.zip"
  - unzip -qq elona122.zip
  - rm elona122.zip
  - cd "$TRAVIS_BUILD_DIR"
  - make clean
  - if [[ "$BUILD_TYPE" == "linux" ]]; then
      make tests VERBOSE=1;
    elif [[ "$BUILD_TYPE" == "osx" ]]; then
      make tests VERBOSE=1;
    elif [[ "$BUILD_TYPE" == "android" ]]; then
      make android;
    fi
  - if [[ "$BUILD_TYPE" == "linux" ]]; then ccache --show-stats; fi

notifications:
  email: false
