shallow_clone: true
clone_folder: C:\projects\ElonaFoobar

os:
  - Visual Studio 2017

environment:
  matrix:
  - CMAKE_ARGS: -G "Visual Studio 15 2017 Win64"
    BOOST_VERSION: 1.66.0
    BOOST_ROOT: C:\Libraries\boost_1_66_0
    PREFIX: C:\SDK

build:
  verbosity: detailed

configuration:
  - Debug


# for master branch
for:
-
  branches:
    only:
      - master

  configuration:
    - Release


branches:
  except:
    - /pr\/.+/

cache:
  C:\SDK -> appveyor.yml

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd C:\projects\ElonaFoobar
  - if exist %PREFIX% set NEEDDEPENDS=rem

  - |-
    %NEEDDEPENDS% mkdir %PREFIX%\include\SDL2
    %NEEDDEPENDS% mkdir %PREFIX%\lib
    %NEEDDEPENDS% cd %TEMP%

  - |-
    %NEEDDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
    %NEEDDEPENDS% 7z x -y SDL2-devel-2.0.8-VC.zip > nul
    %NEEDDEPENDS% copy SDL2-2.0.8\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2-2.0.8\lib\x64\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.2-VC.zip
    %NEEDDEPENDS% 7z x -y SDL2_mixer-devel-2.0.2-VC.zip > nul
    %NEEDDEPENDS% copy SDL2_mixer-2.0.2\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2_mixer-2.0.2\lib\x64\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-VC.zip
    %NEEDDEPENDS% 7z x -y SDL2_ttf-devel-2.0.14-VC.zip > nul
    %NEEDDEPENDS% copy SDL2_ttf-2.0.14\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2_ttf-2.0.14\lib\x64\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile http://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.3-VC.zip
    %NEEDDEPENDS% 7z x -y SDL2_image-devel-2.0.3-VC.zip > nul
    %NEEDDEPENDS% copy SDL2_image-2.0.3\include\* %PREFIX%\include > nul
    %NEEDDEPENDS% copy SDL2_image-2.0.3\lib\x64\* %PREFIX%\lib > nul
  - |-
    %NEEDDEPENDS% appveyor DownloadFile https://www.lua.org/ftp/lua-5.3.4.tar.gz
    %NEEDDEPENDS% mkdir %PREFIX%\lib\lua\src > nul
    %NEEDDEPENDS% copy %APPVEYOR_BUILD_FOLDER%\cmake\lua\* %PREFIX%\lib\lua > nul
    %NEEDDEPENDS% 7z x lua-5.3.4.tar.gz -so | 7z x -aoa -si -ttar > nul
    %NEEDDEPENDS% xcopy /s /e /y lua-5.3.4\src\* %PREFIX%\lib\lua\src > nul
    %NEEDDEPENDS% cd %PREFIX%\lib\lua\src
    %NEEDDEPENDS% patch -p0 --binary < ..\lua_wstring_5.3.4.patch
    %NEEDDEPENDS% cd %TEMP%

build_script:
  - chcp 65001
  - cd %PREFIX%
  - appveyor DownloadFile http://ylvania.style.coocan.jp/file/elona122.zip
  - 7z x -y elona122.zip > nul
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir bin
  - cd bin
  - cmake -DCMAKE_PREFIX_PATH=%PREFIX% -DWITH_TESTS=TESTS %CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%
  - cd %CONFIGURATION%
  - Elona_foobar.exe --durations=yes
  - cd %APPVEYOR_BUILD_FOLDER%\bin
  - cmake -DCMAKE_PREFIX_PATH=%PREFIX% -DWITH_TESTS=OFF %CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mv bin\%CONFIGURATION% bin\Elona_foobar
  - mv CHANGELOG*.md bin\Elona_foobar
  - mv README*.md bin\Elona_foobar
  - mv LICENSE bin\Elona_foobar
  - mv CREDITS bin\Elona_foobar
  - del bin\Elona_foobar\*.ilk
  - del bin\Elona_foobar\*.pdb
  - rd /q /s bin\Elona_foobar\graphic
  - rd /q /s bin\Elona_foobar\original
  - rd /q /s bin\Elona_foobar\sound
  - rd /q /s bin\Elona_foobar\user
  - xcopy /s /e /y runtime\* bin\Elona_foobar
  - cd bin
  - 7z a -y Elona_foobar_windows.zip Elona_foobar

artifacts:
  - path: bin\Elona_foobar_windows.zip

