[package]
name = "elonafoobar-lua"
version = "0.8.0"
authors = ["KI"] # See also ../CREDITS.txt.
edition = "2018"
publish = false

[dependencies]
elonafoobar-lua-sys = { path = "../elonafoobar-lua-sys" }
elonafoobar-utils = { path = "../elonafoobar-utils" }
anyhow = "1.0.37"
bitflags = "1.2.1"
